apiVersion: v1
kind: ConfigMap
metadata:
  name: alert-config
  namespace: monitoring
data:
  config.yml: |-
    global:
      resolve_timeout: 5m
    route:
      receiver: webhook
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 5m
      group_by: [alertname]
      routes:
      - receiver: webhook
        group_wait: 10s
    receivers:
    - name: webhook
      webhook_configs:
      - url: http://10.128.42.140:8060/dingtalk/webhook1/send  
        send_resolved: true
